site_name: MkDocs Run Shell Command Plugin

repo_url: https://github.com/seapagan/mkdocs-run-shell-cmd-plugin
repo_name: mkdocs-run-shell-cmd-plugin
copyright: © 2023 Grant Ramsay (Seapagan)

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - navigation.top

plugins:
  - search
  - run-shell-cmd

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist

extra:
  social:
    - icon: material/web
      link: https://www.gnramsay.com
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay_dev

extra_css:
  - css/extra.css

nav:
  - Documentation:
      - Home: index.md
      - Examples: examples.md
      - TODO List: todo.md
      - License: license.md
