site_name: mkdocs-run-shell-cmd-plugin

theme:
  name: material
  language: en

plugins:
  - search
  - run-shell-cmd

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist

extra_css:
  - css/tasklist.css

nav:
  - Home: index.md
  - Examples: examples.md
  - TODO List: todo.md
  - License: license.md
